services:
  db:
    image: mysql:8.0
    container_name: mysql_logistics_api
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - logistics_net

  redis:
    image: redis:alpine
    container_name: redis_logistics_api
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - logistics_net

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: pma_logistics_api
    restart: always
    environment:
      PMA_HOST: db
    ports:
      - "${PMA_PORT}:80"
    depends_on:
      - db
    networks:
      - logistics_net

  api_node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_logistics_api
    restart: always
    ports:
      - "${API_PORT}:5000"
    environment:
      - API_PORT=5000
      - DATABASE_URL=mysql://root:${DATABASE_PASSWORD}@db:3306/${DATABASE_NAME}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - db
      - redis
    networks:
      - logistics_net

volumes:
  mysql_data:


networks:
  logistics_net:
    driver: bridge
